name: flutter_application_3
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  just_debounce_it: 4.1.0
  photo_view: ^0.14.0
  equatable: 1.2.5
  flutter_bloc: 7.0.1
  provider: 5.0.0
  http: 0.13.5
  html: 0.15.1
  cupertino_icons: ^1.0.2
  cached_network_image: 3.2.0

  flutter:
    sdk: flutter
  intl: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
